# Generated by Django 3.0.4 on 2020-05-28 11:01

from django.db import migrations, models
import django.db.models.deletion
import partial_date.partial_date


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
                ('journal', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('year', partial_date.partial_date.PartialDateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=5, default=0, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=5, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_date', partial_date.partial_date.PartialDateField()),
                ('characteristic', models.CharField(max_length=50)),
                ('functioning_region', models.CharField(max_length=50)),
                ('start_functioning_year', partial_date.partial_date.PartialDateField()),
                ('end_functioning_year', partial_date.partial_date.PartialDateField()),
                ('bibliography', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='installations.Bibliography')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('policy', models.CharField(blank=True, max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=50)),
                ('end_date', partial_date.partial_date.PartialDateField()),
                ('bibliography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Bibliography')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.City')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionnType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
                ('date', partial_date.partial_date.PartialDateField()),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('bibliography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Bibliography')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('birth', partial_date.partial_date.PartialDateField()),
                ('death', partial_date.partial_date.PartialDateField()),
                ('role', models.CharField(blank=True, max_length=100)),
                ('bibliography', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='installations.Bibliography')),
                ('material_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.MaterialEvidence')),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Watersystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('bibliography', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='installations.Bibliography')),
                ('inventor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.Person')),
            ],
        ),
        migrations.CreateModel(
            name='TextualEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
                ('date', partial_date.partial_date.PartialDateField()),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('bibliography', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='installations.Bibliography')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.SourceType')),
            ],
        ),
        migrations.CreateModel(
            name='TextPersonRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=0, max_length=1000)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Person')),
                ('textual_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.TextualEvidence')),
            ],
        ),
        migrations.CreateModel(
            name='TextInstitutionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('institution', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='installations.Institution')),
                ('textual_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.TextualEvidence')),
            ],
        ),
        migrations.CreateModel(
            name='TextInstallationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('installation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
                ('textual_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.TextualEvidence')),
            ],
        ),
        migrations.CreateModel(
            name='PersonInstitutionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('start_date', partial_date.partial_date.PartialDateField()),
                ('end_date', partial_date.partial_date.PartialDateField()),
                ('institution', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='installations.Institution')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonInstallationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('installation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='religion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.Religion'),
        ),
        migrations.AddField(
            model_name='person',
            name='textual_evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.TextualEvidence'),
        ),
        migrations.CreateModel(
            name='MaterialInstallationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('installation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
                ('material_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.MaterialEvidence')),
            ],
        ),
        migrations.AddField(
            model_name='materialevidence',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.SourceType'),
        ),
        migrations.CreateModel(
            name='InstitutionInstallationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
                ('institution', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='installations.Institution')),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='material_evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.MaterialEvidence'),
        ),
        migrations.AddField(
            model_name='institution',
            name='religion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.Religion'),
        ),
        migrations.AddField(
            model_name='institution',
            name='textual_evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.TextualEvidence'),
        ),
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.InstitutionnType'),
        ),
        migrations.CreateModel(
            name='InstallationPurposeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=7)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
                ('purpose', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.Purpose')),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='material_evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.MaterialEvidence'),
        ),
        migrations.AddField(
            model_name='installation',
            name='textual_evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.TextualEvidence'),
        ),
        migrations.AddField(
            model_name='installation',
            name='watersystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Watersystem'),
        ),
        migrations.CreateModel(
            name='CityPersonRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.City')),
                ('person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Citymap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('start_date', partial_date.partial_date.PartialDateField()),
                ('end_date', partial_date.partial_date.PartialDateField()),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='citymaps', to='installations.City')),
            ],
        ),
        migrations.CreateModel(
            name='CityInistallationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_absolute', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('capacity_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.City')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
            ],
        ),
        migrations.CreateModel(
            name='CityEra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', partial_date.partial_date.PartialDateField()),
                ('end_date', partial_date.partial_date.PartialDateField()),
                ('population', models.IntegerField()),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.City')),
            ],
        ),
    ]
