# Generated by Django 3.0.4 on 2020-03-31 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_auto_20200331_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Watersystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('inventor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonInstallationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Person')),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='watersystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Watersystem'),
        ),
        migrations.CreateModel(
            name='CityInistallationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_absolute', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('capacity_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.City')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
            ],
        ),
    ]
