# Generated by Django 2.2.13 on 2020-07-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0003_auto_20200610_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textualevidence',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
