# Generated by Django 3.0.4 on 2020-03-31 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0003_auto_20200401_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('policy', models.CharField(blank=True, max_length=100)),
                ('start_date', models.CharField(blank=True, help_text='Date formats:Day: yyyy-mm-dd 1999-12-04Month: yyyy-mm 1999-12Year: <integer>y 1999yDecade: <integer>d 200d 1990-2000Century: <integer>c 20c 1900-2000Millennium: <integer>m 2m 1000-2000', max_length=50)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.City')),
                ('political_orientation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.Politicalorientation')),
                ('religious_orientation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.Religiousorientation')),
            ],
        ),
        migrations.CreateModel(
            name='Organizationtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PersonOrganizationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.Organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Person')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.Organizationtype'),
        ),
    ]
