# Generated by Django 3.0.4 on 2020-04-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0004_auto_20200401_0135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Religiousorientation',
            new_name='Religion',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='religious_orientation',
            new_name='religion',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='person',
            name='political_orientation',
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='organization',
            name='start_date',
            field=models.CharField(blank=True, help_text='Date formats:Day: yyyy-mm-dd 1999-12-04  Month: yyyy-mm 1999-12  Year: <integer>y 1999y  Decade: <integer>d 200d 1990-2000  Century: <integer>c 20c 1900-2000  Millennium: <integer>m 2m 1000-2000  ', max_length=50),
        ),
    ]
