# Generated by Django 3.0.4 on 2020-04-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0005_auto_20200415_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
                ('journal', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('policy', models.CharField(blank=True, max_length=100)),
                ('start_date', models.CharField(blank=True, help_text='Date formats:Day: yyyy-mm-dd 1999-12-04  Month: yyyy-mm 1999-12  Year: <integer>y 1999y  Decade: <integer>d 200d 1990-2000  Century: <integer>c 20c 1900-2000  Millennium: <integer>m 2m 1000-2000  ', max_length=50)),
                ('bibliography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Bibliography')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
                ('bibliography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Bibliography')),
            ],
        ),
        migrations.CreateModel(
            name='TextualEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('bibliography', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='installations.Bibliography')),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='political_orientation',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='religious_orientation',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='type',
        ),
        migrations.RemoveField(
            model_name='personinstallationrelation',
            name='installation',
        ),
        migrations.RemoveField(
            model_name='personinstallationrelation',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personorganizationrelation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='personorganizationrelation',
            name='person',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RenameModel(
            old_name='Organizationtype',
            new_name='InstitutionnType',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='PersonInstallationRelation',
        ),
        migrations.DeleteModel(
            name='PersonOrganizationRelation',
        ),
        migrations.DeleteModel(
            name='Politicalorientation',
        ),
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.City'),
        ),
        migrations.AddField(
            model_name='institution',
            name='material_evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.MaterialEvidence'),
        ),
        migrations.AddField(
            model_name='institution',
            name='religion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.Religion'),
        ),
        migrations.AddField(
            model_name='institution',
            name='textual_evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.TextualEvidence'),
        ),
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='installations.InstitutionnType'),
        ),
        migrations.AddField(
            model_name='person',
            name='bibliography',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='installations.Bibliography'),
        ),
        migrations.AddField(
            model_name='watersystem',
            name='bibliography',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='installations.Bibliography'),
        ),
    ]
