# Generated by Django 2.2.13 on 2020-07-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0005_auto_20200715_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textualevidence',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
