# Generated by Django 2.2.13 on 2020-07-15 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0006_auto_20200715_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textualevidence',
            name='bibliography',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='installations.Bibliography'),
        ),
        migrations.AlterField(
            model_name='textualevidence',
            name='source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='installations.SourceType'),
        ),
    ]
